version: "4.31.1"

services:
  server:
    image: nginx:1.17-alpine
    container_name: lcp_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./dockerize/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
  php:
    build:
      context: .
      dockerfile: ./dockerize/app/php.dockerfile
    volumes:
      - .:/var/www/html
  mysql:
    platform: linux/x86_64 
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 81:80